---
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/stacks/contoso/env/demo.tfvars

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Infra build
    jobs:
      - job: "buildJob"
  - template: stages/stage.build.yml
    variables:
    - template: variables/variables.demo.yml
