schedules:
  - cron: "30 11 * * *"
    displayName: Construição matutina do Ambiente
    branches:
      include:
        - development
      exclude:
        - main
    always: true

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Stage1
    displayName: Preparing for creation
    jobs:
      - job: job1
        displayName: Gathering Create Template
    variables:
      - group: kv-tf
  - template: stages/stage-apply.yml
