trigger:
  branches:
    include:
    - development
    - main
  paths:  
    exclude:
    - docs/*
    - documents/*
    - .devcontainer/*
    - terraform/bootstrap/*
    - terraform/templates/*
    - templates/*

pool:
  vmImage: ubuntu-latest

stages:

  - stage: CD
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI')) # Essa lógica indica que o Pipe "IndividualCI precisa ter sido bem sucedido para poder começar o CD"
    displayName: Continuous Deployment
    jobs: 
    - job: "CD"
    variables:
    - group: kv-tf
  - template: stages/cd.yml
