---
pr:
  autoCancel: false
  branches:
    include:
      - main
  paths:
    include:
      - terraform/stacks/contoso/demo.tfvars

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: PR
    displayName: Testing Environment
    jobs:
      - job: "prJob"
  - template: stages/stage.pr.yml
    variables:
    - template: variables/variables.demo.yml
