---
steps:
  - task: TerraformCLI@0
    inputs:
      command: 'apply'
      workingDirectory: $(terraformWorkDirectory)
      environmentServiceName: az-connection
      commandOptions: '-var-file=$(TF_WORKSPACE).tfvars'
      allowTelemetryCollection: true
    displayName: 'Terraform Apply'
