---
steps:
    - bash: |
        cd $(System.DefaultWorkingDirectory)
        sudo apt-get update -qq && sudo apt-get -qq install bc curl git
        curl -sL https://github.com/infracost/infracost/releases/latest/download/infracost-linux-amd64.tar.gz | tar xz -C /tmp
        sudo mv /tmp/infracost-linux-amd64 /usr/local/bin/infracost
        curl -sL -o infracost_diff.sh https://raw.githubusercontent.com/infracost/infracost/master/scripts/ci/diff.sh
        chmod +x infracost_diff.sh
        ./infracost_diff.sh
      displayName: Run Infracost diff
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken) # Do not change this, it's used to post comments
        ARM_CLIENT_SECRET: $(ARM-CLIENT-SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM-SUBSCRIPTION-ID)
        INFRACOST_API_KEY: $(INFRACOST-API-KEY)
        ARM_CLIENT_ID: $(ARM-CLIENT-ID)
        ARM_TENANT_ID: $(ARM-TENANT-ID)
        path: 'stacks/contoso'
        terraform_workspace: $(TF_WORKSPACE)
        terraform_plan_flags: '-out=main.tfplan -var-file=./env/$(TF_WORKSPACE).tfvars'
        show_skipped: true
