---
steps:
  - task: TerraformCLI@0
    displayName: Terraform Plan
    inputs:
      command: "plan"
      workingDirectory: $(terraformWorkDirectory)
      environmentServiceName: az-connection
      commandOptions: '-out=main.tfplan -var-file=$(TF_WORKSPACE).tfvars'
      allowTelemetryCollection: true
      publishPlanResults: "Terraform Plan"
